### ISSUE TITLE
Agregar Boton de nuevo documento

### ISSUE THREAD

**Issue by Frandvh** [code-epic/gdoc#12]
- [ ] agregar boton para registar nuevo documento en modulo presidencial
![image](https://github.com/code-epic/gdoc/assets/147665398/16dc5f92-ffc5-4014-8878-a5689e1ba839)

**Comment by andriby** [comment]
Agregado boton para nuevo documento

![Captura desde 2024-04-04 14-23-46](https://github.com/code-epic/gdoc/assets/113264010/09309278-b9ca-4622-a09c-9240cfedd4aa)
