### ISSUE TITLE
Actualizar iconos de Sub menu de Secretaria 

### ISSUE THREAD

**Issue by Frandvh** [code-epic/gdoc#13]
- [ ] actualizar o cambiar iconos de los sub menu del Modulo de secretaria. 
- Buzon 
- Ministeriales
- Presidenciales
- Buscardo
- Consulta

![Snapshot_2024-03-19_14-04-16](https://github.com/code-epic/gdoc/assets/147665398/1a0424e8-3504-4621-8c9f-0491a781266a)

**Comment by andriby** [comment]
Los iconos fueron modificados
![image](https://github.com/code-epic/gdoc/assets/113264010/1d2662bf-8904-46f0-84d8-fbefae1bec85)
