### ISSUE TITLE
Buzon-Secretaria

### ISSUE THREAD

**Issue by Frandvh** [code-epic/gdoc#27]
- [ ]  clasificacion de docuementos

El modulo de Buzon no clasifica el Tipo de documento que se recibe.
Punto de Cuenta
Acuse de Recibo
Entre otros..

![image](https://github.com/code-epic/gdoc/assets/147665398/57a80180-eba4-44ec-bef9-750559d7639e)

**Comment by andriby** [comment]
Ya aparece que tipo de documento recibe

![Captura desde 2024-04-04 15-33-13](https://github.com/code-epic/gdoc/assets/113264010/c3882a07-8873-42ad-a4ac-113a9c12b2db)
