### ISSUE TITLE
Modulo Presidenciales no esta activo

### ISSUE THREAD

**Issue by Frandvh** [code-epic/gdoc#5]
- [ ] Modulo presidencial aun no funciona. 

![image](https://github.com/code-epic/gdoc/assets/147665398/83e3a627-2c13-4570-b845-d5cc235c56d1)

**Comment by Frandvh** [comment]
- [ ] Falta boton para agregar nuevo documento
![image](https://github.com/code-epic/gdoc/assets/147665398/16dc5f92-ffc5-4014-8878-a5689e1ba839)

**Comment by andriby** [comment]
El modulo de Presidenciales ya se encuentra activado 

![Captura desde 2024-03-16 20-56-30](https://github.com/code-epic/gdoc/assets/113264010/c5920f89-a3a0-4e38-89f7-6c9dd6272c0b)
