### ISSUE TITLE
Buscardor de Secretaria

### ISSUE THREAD

**Issue by Frandvh** [code-epic/gdoc#6]
- [ ] Buscador en Seguimiento No Funciona aun

![image](https://github.com/code-epic/gdoc/assets/147665398/0136099f-8429-4377-b3b5-eb4e4e8f5372)

![image](https://github.com/code-epic/gdoc/assets/147665398/6828bf9f-c00c-4fe1-897e-0bbce9afa29e)

**Comment by andriby** [comment]
El buscador de Documentos ya esta habilitado para buscar por numero de cuenta, fecha de recepcion, y estatus del documento

![Captura desde 2024-04-08 17-16-22](https://github.com/code-epic/gdoc/assets/113264010/fc2ac824-588a-4baf-a1a7-8a6d7f9c042c)
